rules = [{'class': 0,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '<=', 0.04)],
  'fuzzy_score': 1.0,
  'samples': 70},
 {'class': 1,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '<=', 0.04)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '<=', 0.13)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.13),
                 ('Property_Area', '<=', 0.71)],
  'fuzzy_score': 1.0,
  'samples': 56},
 {'class': 0,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.13),
                 ('Property_Area', '>', 0.71),
                 ('Dependents_1', '<=', 0.5)],
  'fuzzy_score': 0.5,
  'samples': 11},
 {'class': 1,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.13),
                 ('Property_Area', '>', 0.71),
                 ('Dependents_1', '>', 0.5),
                 ('ApplicantIncome', '<=', 0.08)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.13),
                 ('Property_Area', '>', 0.71),
                 ('Dependents_1', '>', 0.5),
                 ('ApplicantIncome', '>', 0.08)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.13),
                 ('ApplicantIncome', '<=', 0.05)],
  'fuzzy_score': 0.5,
  'samples': 8},
 {'class': 1,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '<=', 0.19),
                 ('TotalIncome', '>', 0.04),
                 ('TotalIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.13),
                 ('ApplicantIncome', '>', 0.05)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '>', 0.19),
                 ('TotalIncome', '<=', 0.16)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '<=', 0.5),
                 ('ApplicantIncome', '<=', 0.35),
                 ('CoapplicantIncome', '>', 0.19),
                 ('TotalIncome', '>', 0.16)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '<=', 0.5), ('ApplicantIncome', '>', 0.35)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '<=', 0.02),
                 ('Gender', '<=', 0.68),
                 ('Loan_Income_Ratio', '<=', 0.01)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '<=', 0.02),
                 ('Gender', '<=', 0.68),
                 ('Loan_Income_Ratio', '>', 0.01)],
  'fuzzy_score': 0.5,
  'samples': 6},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '<=', 0.02),
                 ('Gender', '>', 0.68),
                 ('LoanAmount', '<=', 0.07),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '<=', 0.02),
                 ('Gender', '>', 0.68),
                 ('LoanAmount', '<=', 0.07),
                 ('Loan_Income_Ratio', '>', 0.02)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '<=', 0.02),
                 ('Gender', '>', 0.68),
                 ('LoanAmount', '>', 0.07)],
  'fuzzy_score': 0.5,
  'samples': 7},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '<=', 0.07),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('ApplicantIncome', '<=', 0.04)],
  'fuzzy_score': 0.5,
  'samples': 8},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '<=', 0.07),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('ApplicantIncome', '>', 0.04),
                 ('LoanAmount', '<=', 0.09)],
  'fuzzy_score': 0.25,
  'samples': 3},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '<=', 0.07),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('ApplicantIncome', '>', 0.04),
                 ('LoanAmount', '>', 0.09)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '<=', 0.07),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('CoapplicantIncome', '>', 0.01)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '<=', 0.07),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('CoapplicantIncome', '>', 0.01)],
  'fuzzy_score': 0.75,
  'samples': 48},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '<=', 0.07),
                 ('Loan_Amount_Term', '>', 0.87)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '>', 0.07),
                 ('ApplicantIncome', '<=', 0.03),
                 ('ApplicantIncome', '<=', 0.01)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '>', 0.07),
                 ('ApplicantIncome', '<=', 0.03),
                 ('ApplicantIncome', '>', 0.01)],
  'fuzzy_score': 0.5,
  'samples': 9},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '<=', 0.04),
                 ('CoapplicantIncome', '>', 0.07),
                 ('ApplicantIncome', '>', 0.03)],
  'fuzzy_score': 0.5,
  'samples': 14},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '<=', 0.04),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '<=', 0.04),
                 ('Loan_Income_Ratio', '>', 0.02)],
  'fuzzy_score': 0.5,
  'samples': 5},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '<=', 0.14),
                 ('ApplicantIncome', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.04),
                 ('TotalIncome', '<=', 0.03)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '<=', 0.14),
                 ('ApplicantIncome', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.04),
                 ('TotalIncome', '>', 0.03),
                 ('ApplicantIncome', '<=', 0.04)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '<=', 0.14),
                 ('ApplicantIncome', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.04),
                 ('TotalIncome', '>', 0.03),
                 ('ApplicantIncome', '>', 0.04)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '<=', 0.14),
                 ('ApplicantIncome', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.04)],
  'fuzzy_score': 0.25,
  'samples': 4},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '<=', 0.14),
                 ('ApplicantIncome', '>', 0.04)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '>', 0.14),
                 ('LoanAmount', '<=', 0.24)],
  'fuzzy_score': 0.5,
  'samples': 14},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '>', 0.14),
                 ('LoanAmount', '>', 0.24),
                 ('LoanAmount', '<=', 0.24)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '>', 0.14),
                 ('LoanAmount', '>', 0.24),
                 ('LoanAmount', '>', 0.24)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '<=', 0.71),
                 ('ApplicantIncome', '>', 0.04),
                 ('ApplicantIncome', '>', 0.04),
                 ('Loan_Amount_Term', '>', 0.87)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '>', 0.71),
                 ('LoanAmount', '<=', 0.23),
                 ('Loan_Income_Ratio', '<=', 0.04)],
  'fuzzy_score': 1.0,
  'samples': 70},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '>', 0.71),
                 ('LoanAmount', '<=', 0.23),
                 ('Loan_Income_Ratio', '>', 0.04),
                 ('Gender', '<=', 0.68)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '>', 0.71),
                 ('LoanAmount', '<=', 0.23),
                 ('Loan_Income_Ratio', '>', 0.04),
                 ('Gender', '>', 0.68)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '>', 0.71),
                 ('LoanAmount', '>', 0.23),
                 ('TotalIncome', '<=', 0.05)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '<=', 0.05),
                 ('TotalIncome', '>', 0.02),
                 ('Property_Area', '>', 0.71),
                 ('LoanAmount', '>', 0.23),
                 ('TotalIncome', '>', 0.05)],
  'fuzzy_score': 0.25,
  'samples': 4},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('ApplicantIncome', '<=', 0.12)],
  'fuzzy_score': 0.75,
  'samples': 21},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('ApplicantIncome', '>', 0.12),
                 ('ApplicantIncome', '<=', 0.15),
                 ('Loan_Amount_Term', '<=', 0.62)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('ApplicantIncome', '>', 0.12),
                 ('ApplicantIncome', '<=', 0.15),
                 ('Loan_Amount_Term', '>', 0.62)],
  'fuzzy_score': 0.25,
  'samples': 3},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('ApplicantIncome', '>', 0.12),
                 ('ApplicantIncome', '>', 0.15)],
  'fuzzy_score': 0.5,
  'samples': 8},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '<=', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.75,
  'samples': 21},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '<=', 0.15),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.5,
  'samples': 5},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '<=', 0.15),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('ApplicantIncome', '<=', 0.05)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '<=', 0.15),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('ApplicantIncome', '>', 0.05),
                 ('Education', '<=', 0.66)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '<=', 0.15),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('ApplicantIncome', '>', 0.05),
                 ('Education', '>', 0.66)],
  'fuzzy_score': 0.5,
  'samples': 7},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('Education', '<=', 0.66),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.5,
  'samples': 9},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('Education', '<=', 0.66),
                 ('Loan_Income_Ratio', '>', 0.02)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '<=', 0.01),
                 ('Education', '>', 0.66)],
  'fuzzy_score': 0.5,
  'samples': 12},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '>', 0.01),
                 ('LoanAmount', '<=', 0.25),
                 ('ApplicantIncome', '<=', 0.07),
                 ('ApplicantIncome', '<=', 0.05)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '>', 0.01),
                 ('LoanAmount', '<=', 0.25),
                 ('ApplicantIncome', '<=', 0.07),
                 ('ApplicantIncome', '>', 0.05),
                 ('CoapplicantIncome', '<=', 0.03)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '>', 0.01),
                 ('LoanAmount', '<=', 0.25),
                 ('ApplicantIncome', '<=', 0.07),
                 ('ApplicantIncome', '>', 0.05),
                 ('CoapplicantIncome', '>', 0.03)],
  'fuzzy_score': 0.5,
  'samples': 5},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '>', 0.01),
                 ('LoanAmount', '<=', 0.25),
                 ('ApplicantIncome', '>', 0.07)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '>', 0.01),
                 ('LoanAmount', '>', 0.25),
                 ('TotalIncome', '<=', 0.19)],
  'fuzzy_score': 0.5,
  'samples': 16},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('CoapplicantIncome', '>', 0.01),
                 ('LoanAmount', '>', 0.25),
                 ('TotalIncome', '>', 0.19)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '<=', 0.64),
                 ('Loan_Income_Ratio', '>', 0.03)],
  'fuzzy_score': 0.5,
  'samples': 9},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('LoanAmount', '<=', 0.26)],
  'fuzzy_score': 0.5,
  'samples': 9},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('LoanAmount', '>', 0.26),
                 ('TotalIncome', '<=', 0.15)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('LoanAmount', '>', 0.26),
                 ('TotalIncome', '>', 0.15)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('TotalIncome', '<=', 0.07)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('TotalIncome', '>', 0.07),
                 ('Education', '<=', 0.66)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('TotalIncome', '>', 0.07),
                 ('Education', '>', 0.66)],
  'fuzzy_score': 0.5,
  'samples': 6},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.75,
  'samples': 24},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('ApplicantIncome', '<=', 0.07)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.02),
                 ('ApplicantIncome', '>', 0.07)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Education', '<=', 0.66)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Education', '>', 0.66),
                 ('Loan_Income_Ratio', '<=', 0.02)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Education', '>', 0.66),
                 ('Loan_Income_Ratio', '>', 0.02)],
  'fuzzy_score': 0.5,
  'samples': 7},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Loan_Income_Ratio', '>', 0.03)],
  'fuzzy_score': 0.25,
  'samples': 3},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Married', '<=', 0.67),
                 ('CoapplicantIncome', '<=', 0.02)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Married', '<=', 0.67),
                 ('CoapplicantIncome', '>', 0.02),
                 ('Loan_Income_Ratio', '<=', 0.03)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Married', '<=', 0.67),
                 ('CoapplicantIncome', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Married', '>', 0.67),
                 ('LoanAmount', '<=', 0.18),
                 ('Property_Area', '<=', 0.71)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Married', '>', 0.67),
                 ('LoanAmount', '<=', 0.18),
                 ('Property_Area', '>', 0.71)],
  'fuzzy_score': 0.25,
  'samples': 4},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '<=', 0.18),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Married', '>', 0.67),
                 ('LoanAmount', '>', 0.18)],
  'fuzzy_score': 0.5,
  'samples': 18},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '<=', 0.03),
                 ('Property_Area', '>', 0.64),
                 ('CoapplicantIncome', '>', 0.18)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Gender', '<=', 0.68)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Gender', '>', 0.68),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '<=', 0.45)],
  'fuzzy_score': 0.5,
  'samples': 15},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Gender', '>', 0.68),
                 ('Loan_Amount_Term', '<=', 0.87),
                 ('LoanAmount', '>', 0.45)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '<=', 0.04),
                 ('ApplicantIncome', '>', 0.05),
                 ('Loan_Income_Ratio', '>', 0.02),
                 ('LoanAmount', '>', 0.15),
                 ('Loan_Income_Ratio', '>', 0.03),
                 ('Gender', '>', 0.68),
                 ('Loan_Amount_Term', '>', 0.87)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '>', 0.04),
                 ('Property_Area', '<=', 0.71)],
  'fuzzy_score': 0.5,
  'samples': 19},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '>', 0.04),
                 ('Property_Area', '<=', 0.71)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '>', 0.04),
                 ('Property_Area', '>', 0.71),
                 ('Married', '<=', 0.67)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '<=', 0.21),
                 ('Loan_Income_Ratio', '>', 0.04),
                 ('Property_Area', '>', 0.71),
                 ('Married', '>', 0.67)],
  'fuzzy_score': 0.25,
  'samples': 3},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '<=', 0.44),
                 ('LoanAmount', '<=', 0.83),
                 ('LoanAmount', '<=', 0.15),
                 ('CoapplicantIncome', '<=', 0.65)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '<=', 0.44),
                 ('LoanAmount', '<=', 0.83),
                 ('LoanAmount', '<=', 0.15),
                 ('CoapplicantIncome', '>', 0.65)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '<=', 0.44),
                 ('LoanAmount', '<=', 0.83),
                 ('LoanAmount', '>', 0.15),
                 ('ApplicantIncome', '<=', 0.27)],
  'fuzzy_score': 0.75,
  'samples': 29},
 {'class': 0,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '<=', 0.44),
                 ('LoanAmount', '<=', 0.83),
                 ('LoanAmount', '>', 0.15),
                 ('ApplicantIncome', '>', 0.27),
                 ('Loan_Income_Ratio', '<=', 0.01)],
  'fuzzy_score': 0.25,
  'samples': 3},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '<=', 0.44),
                 ('LoanAmount', '<=', 0.83),
                 ('LoanAmount', '>', 0.15),
                 ('ApplicantIncome', '>', 0.27),
                 ('Loan_Income_Ratio', '>', 0.01)],
  'fuzzy_score': 0.25,
  'samples': 1},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '<=', 0.44),
                 ('LoanAmount', '>', 0.83)],
  'fuzzy_score': 0.25,
  'samples': 2},
 {'class': 1,
  'conditions': [('Credit_History', '>', 0.5),
                 ('TotalIncome', '>', 0.21),
                 ('ApplicantIncome', '>', 0.44)],
  'fuzzy_score': 0.25,
  'samples': 4}]